name: deploy admin lambda

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: checkout master
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: go build
        working-directory: assets/lambda/admin
        run: go build

      - name: zip function
        working-directory: assets/lambda/admin
        run: zip -r function.zip .

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: deploy lambda
        run: aws lambda update-function-code --function-name ${{ secrets.ADMIN_LAMBDA }} --zip-file fileb://function.zip
